#
# This is the configuration file for this site

# title of this site (displayed in the header)
title: Alissa Bader Clark
#
# short bio or description (displayed in the header)
#
name: Alissa Bader Clark
description: Technical Writer
# URL of your avatar or profile pic (you could use your GitHub profile pic)
#
#avatar: https://github.com/alissabaderclark/alissabaderclark.github.io/blob/2617ecfbcd1a3339f91e798363f86ce0c52c1987/images/alissa-mad-men.jpeg
theme: jekyll-theme-dinky
